version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAutomation_AWSDEVProject
  gitServerName: Kusi_VCTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: TPP_services_in_FCS
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
